<script setup lang="ts">
useScript('https://cdn.jsdelivr.net/gh/kangax/html-minifier@gh-pages/dist/htmlminifier.min.js', { trigger: 'client' })

const { t } = useI18n({ useScope: 'local' })

usePageJsonLd({
  name: t('title'),
  description: t('meta'),
  features: [
    t('f_1'),
    t('f_2'),
    t('f_3'),
    t('f_4')
  ],
  howToName: t('how_it_works_title'),
  howToSteps: [
    { name: t('hiw_1_title'), text: t('hiw_1_desc') },
    { name: t('hiw_2_title'), text: t('hiw_2_desc') },
    { name: t('hiw_3_title'), text: t('hiw_3_desc') }
  ],
  faq: [
    { question: t('faq_1_q'), answer: t('faq_1_a') },
    { question: t('faq_2_q'), answer: t('faq_2_a') },
    { question: t('faq_3_q'), answer: t('faq_3_a') }
  ]
})

useHead({
  title: t('m_title'),
  meta: [
    { name: 'description', content: t('meta') }
  ]
})

const state = reactive({
  hasCode: false,
  loaded: false,
  error: '' as string,
  ads: false,
  resetable: false
})

const editor = ref<any>(null)

function onChange() {
  state.hasCode = editor.value!.getValue() !== ''
  state.error = ''
}

function convertOrReset() {
  state.error = ''
  state.resetable ? reset() : minifyCode()
}

function minifyCode() {
  let minifyFn: any
  try {
    minifyFn = (window as any).require('html-minifier').minify
  } catch (error) {
    document.location.reload()
    return
  }

  const options = {
    caseSensitive: true,
    collapseWhitespace: true,
    html5: true,
    includeAutoGeneratedTags: true,
    keepClosingSlash: true,
    minifyCSS: true,
    minifyJS: true,
    removeComments: true,
    collapseBooleanAttributes: true,
    decodeEntities: true,
    processConditionalComments: true,
    removeEmptyAttributes: true,
    removeRedundantAttributes: true,
    trimCustomFragments: true,
    useShortDoctype: true
  }

  try {
    editor.value!.setValue(minifyFn(editor.value!.getValue(), options))
    editor.value!.setReadOnly(true)
    state.resetable = true
    state.ads = true
  } catch (e: any) {
    state.error = `${t('err')}: ${e.message}`
  }
}

function reset() {
  editor.value!.setValue('')
  editor.value!.setReadOnly(false)
  state.resetable = false
  state.hasCode = false
  state.error = ''
}

function copy() {
  navigator.clipboard.writeText(editor.value!.getValue())
}

defineI18nRoute({
  paths: {
    en: '/html-minifier',
    pt: '/minificador-html',
    es: '/minificador-html',
    fr: '/minificateur-html',
    it: '/minificatore-html',
    id: '/html-minifier'
  }
})
</script>

<template>
  <ToolPage
    :title="t('title')"
    :description="t('meta')"
    :show-ads="state.ads"
    :see-also-links="[
      { label: t('see1'), to: 'css-minifier' },
      { label: t('see2'), to: 'javascript-minifier' },
      { label: t('see3'), to: 'html-formatter' },
      { label: t('see4'), to: 'javascript-formatter' }
    ]"
  >
    <div class="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <!-- Loading Placeholder -->
      <div
        v-if="!state.loaded"
        role="status"
        class="flex items-center justify-center h-64 w-full rounded-2xl animate-pulse bg-base-200"
      >
        <Icon name="heroicons:code-bracket" class="w-12 h-12 text-base-content/10" />
      </div>

      <!-- Editor Component -->
      <Editor
        v-show="state.loaded"
        ref="editor"
        lang="html"
        :placeholder="t('plc')"
        @onLoad="state.loaded = true"
        @onChange="onChange"
      />

      <!-- Action Buttons -->
      <div class="flex flex-col sm:flex-row items-center gap-4">
        <ButtonPrimary
          @click="convertOrReset"
          :icon="state.resetable ? 'heroicons:arrow-path-20-solid' : 'heroicons:arrow-right-circle-20-solid'"
          :disabled="!state.hasCode && !state.resetable"
          :class="state.resetable ? 'btn-warning' : ''"
          class="w-full sm:w-auto"
        >
          {{ t(state.resetable ? 'rst' : 'bt') }}
        </ButtonPrimary>

        <Transition
          enter-active-class="transition duration-300 ease-out"
          enter-from-class="transform scale-95 opacity-0"
          enter-to-class="transform scale-100 opacity-100"
        >
          <ButtonIndicator
            v-if="state.resetable"
            @onClick="copy"
            class="w-full sm:w-auto"
          >
            {{ t('copy') }} HTML
          </ButtonIndicator>
        </Transition>
      </div>

      <!-- Error Message -->
      <Transition
        enter-active-class="transition duration-300 ease-out"
        enter-from-class="transform scale-95 opacity-0"
        enter-to-class="transform scale-100 opacity-100"
      >
        <div
          v-if="state.error && state.hasCode"
          class="alert alert-error shadow-lg border-none rounded-2xl text-white flex-col items-start gap-1"
        >
          <div class="flex items-center gap-2">
            <Icon name="heroicons:x-circle-20-solid" class="w-6 h-6" />
            <span class="font-bold">{{ t('err_label') }}</span>
          </div>
          <div class="text-sm opacity-90 font-mono bg-black/20 p-2 rounded-lg w-full mt-1">
            {{ state.error }}
          </div>
        </div>
      </Transition>
    </div>

    <!-- Info Section Content -->
    <template #info>
      <div class="space-y-12">
        <div>
          <p class="text-lg">{{ t('d1') }} {{ t('d2') }}</p>
        </div>

        <!-- How It Works -->
        <section>
          <h2 class="text-2xl font-bold text-base-content mb-6 flex items-center gap-2">
            <Icon name="heroicons:light-bulb" class="text-primary" />
            {{ t('how_it_works_title') }}
          </h2>
          <div class="grid md:grid-cols-3 gap-6">
            <div class="bg-base-200/50 p-6 rounded-2xl border border-base-content/20">
              <div class="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center mb-4">
                <span class="font-bold text-primary text-xl">1</span>
              </div>
              <h3 class="font-bold text-base-content mb-2">{{ t('hiw_1_title') }}</h3>
              <p>{{ t('hiw_1_desc') }}</p>
            </div>
            <div class="bg-base-200/50 p-6 rounded-2xl border border-base-content/20">
              <div class="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center mb-4">
                <span class="font-bold text-primary text-xl">2</span>
              </div>
              <h3 class="font-bold text-base-content mb-2">{{ t('hiw_2_title') }}</h3>
              <p>{{ t('hiw_2_desc') }}</p>
            </div>
            <div class="bg-base-200/50 p-6 rounded-2xl border border-base-content/20">
              <div class="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center mb-4">
                <span class="font-bold text-primary text-xl">3</span>
              </div>
              <h3 class="font-bold text-base-content mb-2">{{ t('hiw_3_title') }}</h3>
              <p>{{ t('hiw_3_desc') }}</p>
            </div>
          </div>
        </section>

        <!-- Use Cases -->
        <section>
          <h2 class="text-2xl font-bold text-base-content mb-6 flex items-center gap-2">
            <Icon name="heroicons:briefcase" class="text-primary" />
            {{ t('use_cases_title') }}
          </h2>
          <div class="bg-base-200/30 rounded-3xl p-8 border border-base-content/20">
            <ul class="grid sm:grid-cols-2 gap-6 list-none p-0 m-0">
              <li class="flex gap-4">
                <div class="mt-1"><Icon name="heroicons:check-circle" class="text-primary w-5 h-5" /></div>
                <div>
                  <strong class="text-base-content block mb-1 uppercase text-xs tracking-widest font-black">{{ t('uc_1_title') }}</strong>
                  <span>{{ t('uc_1_desc') }}</span>
                </div>
              </li>
              <li class="flex gap-4">
                <div class="mt-1"><Icon name="heroicons:check-circle" class="text-primary w-5 h-5" /></div>
                <div>
                  <strong class="text-base-content block mb-1 uppercase text-xs tracking-widest font-black">{{ t('uc_2_title') }}</strong>
                  <span>{{ t('uc_2_desc') }}</span>
                </div>
              </li>
              <li class="flex gap-4 sm:col-span-2">
                <div class="mt-1"><Icon name="heroicons:check-circle" class="text-primary w-5 h-5" /></div>
                <div>
                  <strong class="text-base-content block mb-1 uppercase text-xs tracking-widest font-black">{{ t('uc_3_title') }}</strong>
                  <span>{{ t('uc_3_desc') }}</span>
                </div>
              </li>
            </ul>
          </div>
        </section>

        <!-- FAQ Section -->
        <FaqSection
          :title="t('faq_title')"
          :items="[
            { question: t('faq_1_q'), answer: t('faq_1_a') },
            { question: t('faq_2_q'), answer: t('faq_2_a') },
            { question: t('faq_3_q'), answer: t('faq_3_a') }
          ]"
        />
      </div>
    </template>
  </ToolPage>
</template>

<i18n lang="yaml">
{
    en: {
        m_title: "HTML Minifier Online - Minify & Compress HTML for Free",
        title: "HTML Minifier",
        meta: "Free online HTML minifier. Paste your HTML code and instantly compress it by removing whitespace, comments, and redundant attributes.",
        d1: "This online HTML minifier compresses your markup for production by stripping out whitespace, blank lines, comments, and redundant attributes. Any verbose or development-ready HTML is reduced to the smallest possible size in one click.",
        d2: "It also minifies inline CSS and JavaScript, collapses boolean attributes, and normalizes the doctype, making your pages load faster without changing how they render.",
        plc: "Paste the HTML code here or drag a file",
        bt: "Minify HTML",
        rst: "Start Over",
        copy: "Copy",
        err: "Error",
        err_label: "Could not minify HTML",
        how_it_works_title: "How It Works",
        hiw_1_title: "Paste Your HTML",
        hiw_1_desc: "Copy and paste your HTML source code into the editor.",
        hiw_2_title: "Click Minify",
        hiw_2_desc: "Press the Minify HTML button and the tool will compress the code instantly.",
        hiw_3_title: "Copy the Result",
        hiw_3_desc: "Copy the minified output or start over with new code.",
        use_cases_title: "Use Cases",
        uc_1_title: "Production Deployment",
        uc_1_desc: "Reduce HTML file size before deploying to production for faster page loads and lower bandwidth usage.",
        uc_2_title: "Template Optimization",
        uc_2_desc: "Minify HTML templates in web apps or email campaigns to improve performance and deliverability.",
        uc_3_title: "Lighthouse & Core Web Vitals",
        uc_3_desc: "Smaller HTML payloads directly improve Time to First Byte and First Contentful Paint scores.",
        faq_title: "Questions & Answers",
        faq_1_q: "Is my HTML code sent to any server?",
        faq_1_a: "No. All minification is done entirely in your browser. Your code never leaves your device.",
        faq_2_q: "Does minification break my HTML?",
        faq_2_a: "No. The minifier only removes whitespace, comments, and redundant attributes that have no effect on rendering. The output is functionally identical to the original.",
        faq_3_q: "What happens if my HTML has syntax errors?",
        faq_3_a: "If the HTML cannot be parsed, the tool will display an error message so you can identify and fix the issue before minifying.",
        see1: "CSS Minifier",
        see2: "JavaScript Minifier",
        see3: "HTML Formatter",
        see4: "JavaScript Formatter",
        f_1: "Instant HTML compression and minification",
        f_2: "Removes whitespace, comments, and redundant attributes",
        f_3: "Inline CSS and JavaScript minification",
        f_4: "No registration or installation required"
    },
    pt: {
        m_title: "Minificador de HTML Online - Minifique e Comprima HTML Grátis",
        title: "Minificador de HTML",
        meta: "Minifique HTML online e otimize seu código para produção removendo espaços, quebras de linha e comentários.",
        d1: "Este minificador de HTML online comprime seu código para produção removendo espaços desnecessários, linhas em branco, quebras de linha, comentários e atributos redundantes. Qualquer HTML verboso é reduzido ao menor tamanho possível com um clique.",
        d2: "Ele também minifica CSS e JavaScript embutidos, colapsa atributos booleanos e normaliza o doctype, tornando suas páginas mais rápidas sem alterar a forma como são renderizadas.",
        plc: "Cole o código HTML aqui ou arraste um arquivo",
        bt: "Minificar HTML",
        rst: "Recomeçar",
        copy: "Copiar",
        err: "Erro",
        err_label: "Não foi possível minificar o HTML",
        how_it_works_title: "Como Funciona",
        hiw_1_title: "Cole seu HTML",
        hiw_1_desc: "Copie e cole o código-fonte HTML no editor.",
        hiw_2_title: "Clique em Minificar",
        hiw_2_desc: "Pressione o botão Minificar HTML e o código será comprimido instantaneamente.",
        hiw_3_title: "Copie o Resultado",
        hiw_3_desc: "Copie o HTML minificado ou recomece com um novo código.",
        use_cases_title: "Casos de Uso",
        uc_1_title: "Deploy em Produção",
        uc_1_desc: "Reduza o tamanho dos arquivos HTML antes de publicar em produção para carregamentos mais rápidos e menor uso de banda.",
        uc_2_title: "Otimização de Templates",
        uc_2_desc: "Minifique templates HTML em aplicações web ou campanhas de e-mail para melhorar desempenho e entregabilidade.",
        uc_3_title: "Lighthouse e Core Web Vitals",
        uc_3_desc: "Payloads HTML menores melhoram diretamente o Time to First Byte e os scores de First Contentful Paint.",
        faq_title: "Perguntas e Respostas",
        faq_1_q: "Meu código HTML é enviado para algum servidor?",
        faq_1_a: "Não. Todo o processamento é feito no seu navegador. Seu código nunca sai do seu dispositivo.",
        faq_2_q: "A minificação quebra meu HTML?",
        faq_2_a: "Não. O minificador remove apenas espaços, comentários e atributos redundantes que não afetam a renderização. O resultado é funcionalmente idêntico ao original.",
        faq_3_q: "O que acontece se meu HTML tiver erros de sintaxe?",
        faq_3_a: "Se o HTML não puder ser analisado, a ferramenta exibirá uma mensagem de erro para você identificar e corrigir o problema antes de minificar.",
        see1: "Minificador de CSS",
        see2: "Minificador JavaScript",
        see3: "Formatador HTML",
        see4: "Formatador JavaScript",
        f_1: "Compressão e minificação instantânea de HTML",
        f_2: "Remove espaços, comentários e atributos redundantes",
        f_3: "Minificação de CSS e JavaScript embutidos",
        f_4: "Sem necessidade de cadastro ou instalação"
    },
    es: {
        m_title: "Minificador HTML Online - Minifica y Comprime HTML Gratis",
        title: "Minificador HTML",
        meta: "Minificador HTML online gratuito. Pega tu código HTML y comprímelo al instante eliminando espacios, comentarios y atributos redundantes.",
        d1: "Este minificador HTML online comprime tu código para producción eliminando espacios en blanco, líneas vacías, comentarios y atributos redundantes. Cualquier HTML verboso se reduce al menor tamaño posible con un clic.",
        d2: "También minifica CSS y JavaScript en línea, colapsa atributos booleanos y normaliza el doctype, haciendo que tus páginas carguen más rápido sin cambiar cómo se renderizan.",
        plc: "Pega el código HTML aquí o arrastra un archivo",
        bt: "Minificar HTML",
        rst: "Recomenzar",
        copy: "Copiar",
        err: "Error",
        err_label: "No se pudo minificar el HTML",
        how_it_works_title: "Cómo Funciona",
        hiw_1_title: "Pega tu HTML",
        hiw_1_desc: "Copia y pega el código fuente HTML en el editor.",
        hiw_2_title: "Haz clic en Minificar",
        hiw_2_desc: "Pulsa el botón Minificar HTML y el código se comprimirá al instante.",
        hiw_3_title: "Copia el Resultado",
        hiw_3_desc: "Copia el HTML minificado o empieza de nuevo con código nuevo.",
        use_cases_title: "Casos de Uso",
        uc_1_title: "Despliegue en Producción",
        uc_1_desc: "Reduce el tamaño de los archivos HTML antes de desplegarlos en producción para cargas más rápidas y menor uso de ancho de banda.",
        uc_2_title: "Optimización de Plantillas",
        uc_2_desc: "Minifica plantillas HTML en aplicaciones web o campañas de email para mejorar el rendimiento y la entregabilidad.",
        uc_3_title: "Lighthouse y Core Web Vitals",
        uc_3_desc: "Los payloads HTML más pequeños mejoran directamente el Time to First Byte y las puntuaciones de First Contentful Paint.",
        faq_title: "Preguntas y Respuestas",
        faq_1_q: "¿Mi código HTML se envía a algún servidor?",
        faq_1_a: "No. Todo el procesamiento se realiza en tu navegador. Tu código nunca sale de tu dispositivo.",
        faq_2_q: "¿La minificación rompe mi HTML?",
        faq_2_a: "No. El minificador solo elimina espacios, comentarios y atributos redundantes que no afectan al renderizado. El resultado es funcionalmente idéntico al original.",
        faq_3_q: "¿Qué ocurre si mi HTML tiene errores de sintaxis?",
        faq_3_a: "Si el HTML no se puede analizar, la herramienta mostrará un mensaje de error para que puedas identificar y solucionar el problema antes de minificar.",
        see1: "Minificador CSS",
        see2: "Minificador JavaScript",
        see3: "Formateador HTML",
        see4: "Formateador JavaScript",
        f_1: "Compresión y minificación instantánea de HTML",
        f_2: "Elimina espacios, comentarios y atributos redundantes",
        f_3: "Minificación de CSS y JavaScript en línea",
        f_4: "Sin necesidad de registro ni instalación"
    },
    fr: {
        m_title: "Minificateur HTML en Ligne - Minifiez et Compressez HTML Gratuitement",
        title: "Minificateur HTML",
        meta: "Minificateur HTML en ligne gratuit. Collez votre code HTML et compressez-le instantanément en supprimant les espaces, commentaires et attributs redondants.",
        d1: "Ce minificateur HTML en ligne compresse votre code pour la production en supprimant les espaces, les lignes vides, les commentaires et les attributs redondants. Tout HTML verbeux est réduit à la taille minimale possible en un clic.",
        d2: "Il minifie également le CSS et le JavaScript en ligne, réduit les attributs booléens et normalise le doctype, rendant vos pages plus rapides sans modifier leur rendu.",
        plc: "Collez le code HTML ici ou faites glisser un fichier",
        bt: "Minifier HTML",
        rst: "Recommencer",
        copy: "Copier",
        err: "Erreur",
        err_label: "Impossible de minifier le HTML",
        how_it_works_title: "Comment Ça Marche",
        hiw_1_title: "Collez Votre HTML",
        hiw_1_desc: "Copiez et collez le code source HTML dans l'éditeur.",
        hiw_2_title: "Cliquez sur Minifier",
        hiw_2_desc: "Appuyez sur le bouton Minifier HTML et le code sera compressé instantanément.",
        hiw_3_title: "Copiez le Résultat",
        hiw_3_desc: "Copiez le HTML minifié ou recommencez avec un nouveau code.",
        use_cases_title: "Cas d'Utilisation",
        uc_1_title: "Déploiement en Production",
        uc_1_desc: "Réduisez la taille des fichiers HTML avant le déploiement en production pour des chargements plus rapides et une moindre consommation de bande passante.",
        uc_2_title: "Optimisation de Templates",
        uc_2_desc: "Minifiez les templates HTML dans des applications web ou des campagnes email pour améliorer les performances et la délivrabilité.",
        uc_3_title: "Lighthouse et Core Web Vitals",
        uc_3_desc: "Des payloads HTML plus légers améliorent directement le Time to First Byte et les scores de First Contentful Paint.",
        faq_title: "Questions et Réponses",
        faq_1_q: "Mon code HTML est-il envoyé à un serveur ?",
        faq_1_a: "Non. Tout le traitement est effectué dans votre navigateur. Votre code ne quitte jamais votre appareil.",
        faq_2_q: "La minification casse-t-elle mon HTML ?",
        faq_2_a: "Non. Le minificateur supprime uniquement les espaces, commentaires et attributs redondants qui n'ont aucun effet sur le rendu. Le résultat est fonctionnellement identique à l'original.",
        faq_3_q: "Que se passe-t-il si mon HTML contient des erreurs de syntaxe ?",
        faq_3_a: "Si le HTML ne peut pas être analysé, l'outil affichera un message d'erreur pour vous aider à identifier et corriger le problème avant la minification.",
        see1: "Minificateur CSS",
        see2: "Minificateur JavaScript",
        see3: "Formateur HTML",
        see4: "Formateur JavaScript",
        f_1: "Compression et minification instantanée du HTML",
        f_2: "Suppression des espaces, commentaires et attributs redondants",
        f_3: "Minification du CSS et JavaScript en ligne",
        f_4: "Aucune inscription ou installation requise"
    },
    it: {
        m_title: "Minificatore HTML Online - Minifica e Comprimi HTML Gratis",
        title: "Minificatore HTML",
        meta: "Minificatore HTML online gratuito. Incolla il tuo codice HTML e comprimilo istantaneamente rimuovendo spazi, commenti e attributi ridondanti.",
        d1: "Questo minificatore HTML online comprime il tuo codice per la produzione rimuovendo spazi bianchi, righe vuote, commenti e attributi ridondanti. Qualsiasi HTML prolisso viene ridotto alla dimensione minima possibile con un clic.",
        d2: "Minifica anche CSS e JavaScript inline, riduce gli attributi booleani e normalizza il doctype, rendendo le tue pagine più veloci senza modificarne il rendering.",
        plc: "Incolla il codice HTML qui o trascina un file",
        bt: "Minifica HTML",
        rst: "Ricomincia",
        copy: "Copia",
        err: "Errore",
        err_label: "Impossibile minificare l'HTML",
        how_it_works_title: "Come Funziona",
        hiw_1_title: "Incolla il tuo HTML",
        hiw_1_desc: "Copia e incolla il codice sorgente HTML nell'editor.",
        hiw_2_title: "Clicca su Minifica",
        hiw_2_desc: "Premi il pulsante Minifica HTML e il codice verrà compresso all'istante.",
        hiw_3_title: "Copia il Risultato",
        hiw_3_desc: "Copia l'HTML minificato o ricomincia con un nuovo codice.",
        use_cases_title: "Casi d'Uso",
        uc_1_title: "Deploy in Produzione",
        uc_1_desc: "Riduci la dimensione dei file HTML prima del deploy in produzione per caricamenti più veloci e minore utilizzo di banda.",
        uc_2_title: "Ottimizzazione di Template",
        uc_2_desc: "Minifica i template HTML in applicazioni web o campagne email per migliorare le prestazioni e la recapitabilità.",
        uc_3_title: "Lighthouse e Core Web Vitals",
        uc_3_desc: "Payload HTML più piccoli migliorano direttamente il Time to First Byte e i punteggi di First Contentful Paint.",
        faq_title: "Domande e Risposte",
        faq_1_q: "Il mio codice HTML viene inviato a qualche server?",
        faq_1_a: "No. Tutta l'elaborazione avviene nel tuo browser. Il tuo codice non lascia mai il tuo dispositivo.",
        faq_2_q: "La minificazione rompe il mio HTML?",
        faq_2_a: "No. Il minificatore rimuove solo spazi, commenti e attributi ridondanti che non hanno effetto sul rendering. Il risultato è funzionalmente identico all'originale.",
        faq_3_q: "Cosa succede se il mio HTML ha errori di sintassi?",
        faq_3_a: "Se l'HTML non può essere analizzato, lo strumento mostrerà un messaggio di errore per aiutarti a identificare e correggere il problema prima della minificazione.",
        see1: "Minificatore di CSS",
        see2: "Minificatore JavaScript",
        see3: "Formattatore HTML",
        see4: "Formattatore JavaScript",
        f_1: "Compressione e minificazione istantanea dell'HTML",
        f_2: "Rimozione di spazi, commenti e attributi ridondanti",
        f_3: "Minificazione di CSS e JavaScript inline",
        f_4: "Nessuna registrazione o installazione richiesta"
    },
    id: {
        m_title: "Minifikasi HTML Online - Minifikasi & Kompresi HTML Gratis",
        title: "Minifikasi HTML",
        meta: "Minifikasi HTML online gratis. Tempelkan kode HTML Anda dan kompres secara instan dengan menghapus spasi, komentar, dan atribut berlebih.",
        d1: "Minifikasi HTML online ini mengompres kode Anda untuk produksi dengan menghapus spasi kosong, baris kosong, komentar, dan atribut yang berlebih. Semua HTML yang panjang dikurangi ke ukuran terkecil yang mungkin dalam satu klik.",
        d2: "Alat ini juga meminifikasi CSS dan JavaScript inline, menyederhanakan atribut boolean, dan menormalkan doctype, sehingga halaman Anda memuat lebih cepat tanpa mengubah tampilannya.",
        plc: "Tempel kode HTML di sini atau seret file",
        bt: "Minifikasi HTML",
        rst: "Mulai Ulang",
        copy: "Salin",
        err: "Kesalahan",
        err_label: "Tidak dapat minifikasi HTML",
        how_it_works_title: "Cara Kerja",
        hiw_1_title: "Tempel HTML Anda",
        hiw_1_desc: "Salin dan tempel kode sumber HTML ke dalam editor.",
        hiw_2_title: "Klik Minifikasi",
        hiw_2_desc: "Tekan tombol Minifikasi HTML dan kode akan dikompres secara instan.",
        hiw_3_title: "Salin Hasilnya",
        hiw_3_desc: "Salin HTML yang telah diminifikasi atau mulai ulang dengan kode baru.",
        use_cases_title: "Contoh Penggunaan",
        uc_1_title: "Deploy ke Produksi",
        uc_1_desc: "Kurangi ukuran file HTML sebelum deploy ke produksi untuk pemuatan lebih cepat dan penggunaan bandwidth lebih rendah.",
        uc_2_title: "Optimasi Template",
        uc_2_desc: "Minifikasi template HTML di aplikasi web atau kampanye email untuk meningkatkan performa dan ketercapaian.",
        uc_3_title: "Lighthouse dan Core Web Vitals",
        uc_3_desc: "Payload HTML yang lebih kecil secara langsung meningkatkan Time to First Byte dan skor First Contentful Paint.",
        faq_title: "Tanya Jawab",
        faq_1_q: "Apakah kode HTML saya dikirim ke server?",
        faq_1_a: "Tidak. Semua pemrosesan dilakukan di browser Anda. Kode Anda tidak pernah meninggalkan perangkat Anda.",
        faq_2_q: "Apakah minifikasi merusak HTML saya?",
        faq_2_a: "Tidak. Minifikasi hanya menghapus spasi, komentar, dan atribut berlebih yang tidak memengaruhi rendering. Hasilnya identik secara fungsional dengan aslinya.",
        faq_3_q: "Apa yang terjadi jika HTML saya memiliki kesalahan sintaks?",
        faq_3_a: "Jika HTML tidak dapat diurai, alat ini akan menampilkan pesan kesalahan agar Anda dapat mengidentifikasi dan memperbaiki masalah sebelum minifikasi.",
        see1: "Minifikasi CSS",
        see2: "Minifikasi JavaScript",
        see3: "Pemformat HTML",
        see4: "Pemformat JavaScript",
        f_1: "Kompresi dan minifikasi HTML secara instan",
        f_2: "Menghapus spasi, komentar, dan atribut berlebih",
        f_3: "Minifikasi CSS dan JavaScript inline",
        f_4: "Tanpa pendaftaran atau instalasi"
    }
}
</i18n>
